// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/edb64e4a35896510ce02b93c0bca5ec3878db738/moment/moment.d.ts
declare var moment: moment.MomentStatic;
